import type { VocabItem, PracticeItem } from './types'

export const vocab: VocabItem[] = [
  // From "The Richness of Routine"
  { word: 'meaningful', translation: 'משמעותי', example: 'Getting married and having kids are very meaningful decisions.', source: 'routine' },
  { word: 'recall', translation: 'לזכור', example: 'I recalled my first day of school and smiled.', source: 'routine' },
  { word: 'suggest', translation: 'להציע', example: 'Can you suggest a good movie?', source: 'routine' },
  { word: 'mundane', translation: 'שגרתי, ארצי', example: 'Doing laundry is a mundane task.', source: 'routine' },
  { word: 'regularity', translation: 'שגרתי, סדירות', example: 'To create discipline, you need to perform tasks with some regularity.', source: 'routine' },
  { word: 'squishy', translation: 'רך / לא חד משמעי', example: 'Emotions and feelings are squishy concepts; they are not scientific.', source: 'routine' },
  { word: 'integral', translation: 'חשוב, חיוני / בלתי נפרד', example: 'Good communication is an integral part of teamwork.', source: 'routine' },
  { word: 'propose', translation: 'להציע', example: 'The businessman proposed a new plan to his boss.', source: 'routine' },
  { word: 'pattern', translation: 'תבנית, דפוס', example: 'I notice a pattern in how he answers questions.', source: 'routine' },
  { word: 'engender', translation: 'לעורר, לגרום', example: 'Kind words can engender trust.', source: 'routine' },
  { word: 'random', translation: 'אקראי', example: 'We chose a random option from the list.', source: 'routine' },
  { word: 'seasonal', translation: 'עונתי', example: 'The weather has clear seasonal patterns.', source: 'routine' },
  { word: 'triad', translation: 'שלישייה, שלושה', example: 'There are a triad of words with something in common.', source: 'routine' },
  { word: 'researchers', translation: 'חוקרים', example: 'Researchers study animal behavior.', source: 'routine' },
  { word: 'coherent', translation: 'קוהרנטי, עקבי, מובן', example: 'Psychologists check if someone’s speech is coherent.', source: 'routine' },
  { word: 'mindful', translation: 'מודעות / להיות מודע', example: 'You need to be mindful of the decisions you make.', source: 'routine' },

  // From "Nomophobia"
  { word: 'questionnaire', translation: 'שאלון', source: 'nomophobia' },
  { word: 'phenomenon', translation: 'תופעה', source: 'nomophobia' },
  { word: 'dependence', translation: 'תלות', source: 'nomophobia' },
  { word: 'devices', translation: 'מכשירים', source: 'nomophobia' },
  { word: 'embarrassing', translation: 'מביך', source: 'nomophobia' },
  { word: 'recently', translation: 'לאחרונה', source: 'nomophobia' },
  { word: 'realize', translation: 'להבין', source: 'nomophobia' },
  { word: 'unfortunately', translation: 'לצערי / מצער', source: 'nomophobia' },
  { word: 'incident', translation: 'תקרית', source: 'nomophobia' },
  { word: 'reveals', translation: 'מגלה / חושף', source: 'nomophobia' },
  { word: 'anxiety', translation: 'חרדה', source: 'nomophobia' },
  { word: 'distress', translation: 'מצוקה', source: 'nomophobia' },
  { word: 'navigate', translation: 'לנווט', source: 'nomophobia' },
  { word: 'consequences', translation: 'השלכות', source: 'nomophobia' },
  { word: 'reliable', translation: 'אמין', source: 'nomophobia' },
  { word: 'acquire', translation: 'לרכוש', source: 'nomophobia' },
  { word: 'retain', translation: 'לשמור', source: 'nomophobia' },
  { word: 'omniscience', translation: 'לדעת הכל', source: 'nomophobia' },
  { word: 'publish', translation: 'להוציא לאור', source: 'nomophobia' },
  { word: 'constant', translation: 'קבוע', source: 'nomophobia' },
  { word: 'calculate', translation: 'לחשב', source: 'nomophobia' },
  { word: 'categorizing', translation: 'לסווג, למיין', source: 'nomophobia' },
  { word: 'distinct', translation: 'מובהק', source: 'nomophobia' },
  { word: 'contributed', translation: 'תרם', source: 'nomophobia' },
  { word: 'administer', translation: 'לנהל, לחלק', source: 'nomophobia' },
  { word: 'validate', translation: 'לתקף, לאמת', source: 'nomophobia' },
  { word: 'variables', translation: 'משתנים', source: 'nomophobia' },
  { word: 'correlate', translation: 'לקשר', source: 'nomophobia' },
]

export const practice: PracticeItem[] = [
  { sentenceWithBlank: 'Good communication is an _____ part of teamwork.', answer: 'integral', hint: 'חשוב/חיוני/בלתי נפרד' },
  { sentenceWithBlank: 'Doing laundry is a ______ task for most people.', answer: 'mundane', hint: 'שגרתי' },
  { sentenceWithBlank: 'Kind words can ______ trust between people.', answer: 'engender', hint: 'לגרום/לעורר' },
  { sentenceWithBlank: 'I can’t ______ where I put my keys.', answer: 'recall', hint: 'לזכור' },
  { sentenceWithBlank: 'Can you ______ a good app for learning English?', answer: 'suggest', hint: 'להציע' },
  { sentenceWithBlank: 'The study used a short ______ to collect answers from students.', answer: 'questionnaire', hint: 'שאלון' },
  { sentenceWithBlank: 'This new social media ______ is interesting.', answer: 'phenomenon', hint: 'תופעה' },
  { sentenceWithBlank: 'Too much phone ______ can cause anxiety.', answer: 'dependence', hint: 'תלות' },
  { sentenceWithBlank: 'Modern ______ are useful, but we need balance.', answer: 'devices', hint: 'מכשירים' },
  { sentenceWithBlank: 'She felt ______ after dropping her phone in public.', answer: 'embarrassing', hint: 'מביך' },
  { sentenceWithBlank: 'I ______ that I forgot to send the message.', answer: 'realize', hint: 'מבין/הבין' },
  { sentenceWithBlank: '__________, the train was canceled.', answer: 'Unfortunately', hint: 'לצערי' },
  { sentenceWithBlank: 'The report ______ a surprising pattern.', answer: 'reveals', hint: 'מגלה/חושף' },
  { sentenceWithBlank: 'Breathing exercises can reduce ______ and distress.', answer: 'anxiety', hint: 'חרדה' },
  { sentenceWithBlank: 'Use the map to ______ to the museum.', answer: 'navigate', hint: 'לנווט' },
  { sentenceWithBlank: 'Every action has ______.', answer: 'consequences', hint: 'השלכות' },
  { sentenceWithBlank: 'This source is ______; you can trust it.', answer: 'reliable', hint: 'אמין' },
  { sentenceWithBlank: 'We can ______ knowledge through practice and reading.', answer: 'acquire', hint: 'לרכוש' },
  { sentenceWithBlank: 'Use spaced repetition to ______ new words.', answer: 'retain', hint: 'לשמור' },
  { sentenceWithBlank: 'Scientists avoid ______ choices; they prefer data.', answer: 'random', hint: 'אקראי' },
  { sentenceWithBlank: 'The test ______ your total score after each section.', answer: 'calculates', hint: 'לחשב' },
  { sentenceWithBlank: 'We are ______ results to understand the differences.', answer: 'categorizing', hint: 'לסווג/למיין' },
  { sentenceWithBlank: 'There is a ______ difference between the two groups.', answer: 'distinct', hint: 'מובהק' },
  { sentenceWithBlank: 'Many factors ______ to the final outcome.', answer: 'contributed', hint: 'תרמו' },
  { sentenceWithBlank: 'The teacher will ______ the test to all classes tomorrow.', answer: 'administer', hint: 'לנהל/לחלק' },
  { sentenceWithBlank: 'We must ______ the survey to ensure accurate data.', answer: 'validate', hint: 'לתקף/לאמת' },
  { sentenceWithBlank: 'The ______ in this study include age and screen time.', answer: 'variables', hint: 'משתנים' },
  { sentenceWithBlank: 'We will ______ phone use with stress levels.', answer: 'correlate', hint: 'לקשר' },
]
